apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTERNAME}
  namespace: ${NAMESPACE}
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.10.0.0/16"]
    pods:
      cidrBlocks: ["10.20.0.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: custom-tanzukubernetescluster
    version: v1.23.8---vmware.2-tkg.2-zshippable
    controlPlane:
      replicas: 1
#      variables:
#        overrides:
#        - name: vmClass
#          value: best-effort-large
#      metadata:
#        annotations:
#          run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
    workers:
      machineDeployments:
        - class: node-pool
          name: node-pool-1
          replicas: 1
#          variables:
#            overrides:
#            - name: vmClass
#              value: best-effort-large
#          metadata:
#            annotations:
#              run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
        - class: node-pool
          name: node-pool-2
          replicas: 0
#          variables:
#            overrides:
#            - name: vmClass
#              value: best-effort-large
#          metadata:
#            annotations:
#              run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
        - class: node-pool
          name: node-pool-3
          replicas: 0
#          variables:
#            overrides:
#            - name: vmClass
#              value: best-effort-large
#          metadata:
#            annotations:
#              run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
    variables:
      - name: vmClass
        value: best-effort-medium
      - name: storageClass
        value: tanzu
      - name: defaultStorageClass
        value: tanzu
# ADDITIONAL VALUES
      - name: nodePoolVolumes
        value:
        - capacity:
            storage: "30Gi"
          mountPath: "/var/lib/containerd"
          name: containerd
          storageClass: tanzu
      - name: controlPlaneVolumes
        value:
        - capacity:
            storage: "4Gi"
          mountPath: "/var/lib/etcd"
          name: etcd
          storageClass: tanzu
# Lines below REQUIRED for custom cluster class
      - name: ntp
        value: "time.vmware.com"
      - name: extensionCert
        value:
          contentSecret:
            key: tls.crt
            name: ${CLUSTERNAME}-extensions-ca
      - name: clusterEncryptionConfigYaml
        value: LS0tCmFwaVZlcnNpb246IGFwaXNlcnZlci5jb25maWcuazhzLmlvL3YxCmtpbmQ6IEVuY3J5cHRpb25Db25maWd1cmF0aW9uCnJlc291cmNlczoKICAtIHJlc291cmNlczoKICAgIC0gc2VjcmV0cwogICAgcHJvdmlkZXJzOgogICAgLSBhZXNjYmM6CiAgICAgICAga2V5czoKICAgICAgICAtIG5hbWU6IGtleTEKICAgICAgICAgIHNlY3JldDogdUlkZWtJZTVKZk1qSmpPSWJxM004TnE3K29hcmtCZVF3YUQ5aGFwYnRBaz0KICAgIC0gaWRlbnRpdHk6IHt9Cg==
      - name: user
        value:
          passwordSecret:
            key: ssh-passwordkey
            name: ${CLUSTERNAME}-ssh-password-hashed
          sshAuthorizedKey: |
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC68ipWzsJ4U7im33PdKVUwnV8KJE89h9SnUqdTG+XvPRUqnED0yxeEUmjVR/Mg2AY9ZYlDQ0aHKozXqDnXWkH9Q3bqGD4BrUamrhMy9OqB6AfMHQgxZLBjPxRKxncil2ja6wSf7lwdekVIDAYmYjrqCkswC9LdX5df5frheddWN0I1yiDJyzkdc8sradsLPe9SR2mjnWDycB5S5aRejvO3L5QzUyBAftoZd4OqZ9pngSJ/ULgyLpSSWNPLv9oDa6+DlIzthif4vzLDTar6ky8OYS/SRG5kMbBYL+Re0NbumRUltLC9IR24aPdER0EeaoTIJCtz3smJCoSlGwSkp6vN1r3hsHZAeGR5u995NkP8q4r9yuONr5giqLFV2rhud15iE54FF7WHuj6bSwBQ0F3qfDirigVP1wsyX9Ztd2zIsnLoOwnlPus24XvnbVLAF+b1wR9YasK475alnBdrEuH1oAryNYf5bHRTVfD0QYNIpax/fHclB1HzNU8aPQdCS6WxztGaxsraaWHmxJZV2DooDxZ0fvdUKcWZAufuUD4zKuIIPRuQrHcmYMeKUx3mIH61D/EJWb11mkc2ChKmB7b8b/wBKNaP3Mrx0Bt+91a8LYHgtrMBp0JJUDjSZ338KTnNcJhi0TYHVU/APL9O+BDSg6UXn5vRZv3ey+lqJ+1S5w==
